/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.90
 * Generated at: 2024-11-09 05:52:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class TrangChu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/HocTap/JAVA4/apache-tomcat-9.0.90/wtpwebapps/asm/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1719291191888L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".card-body a {\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".text-truncate {\r\n");
      out.write("    display: -webkit-box;\r\n");
      out.write("    -webkit-line-clamp: 2; /* Số dòng bạn muốn giới hạn */\r\n");
      out.write("    -webkit-box-orient: vertical;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    text-overflow: ellipsis;\r\n");
      out.write("    white-space: normal;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<div class=\"col-12 col-lg-11 px-4\">\r\n");
      out.write("    <div id=\"carouselExample\" class=\"carousel slide w-100\">\r\n");
      out.write("        <div class=\"carousel-inner\">\r\n");
      out.write("            <div class=\"carousel-item active ml-4\">\r\n");
      out.write("                <div class=\"overflow-auto d-flex gap-2 align-items-center mx-lg-4 px-lg-4\">\r\n");
      out.write("                    <button class=\"btn\" style=\"font-size: 14px\">Tất cả</button>\r\n");
      out.write("                    <button class=\"btn\" style=\"font-size: 14px\">Âm nhạc</button>\r\n");
      out.write("                    <button class=\"btn\" style=\"font-size: 14px\">Thể thao</button>\r\n");
      out.write("                    <button class=\"btn\" style=\"font-size: 14px\">Đời sống</button>\r\n");
      out.write("                    <button class=\"btn\" style=\"font-size: 14px\">Học tập</button>\r\n");
      out.write("                    <button class=\"btn\" style=\"font-size: 14px\">Trò chơi</button>\r\n");
      out.write("                    <button class=\"btn\" style=\"font-size: 14px\">Danh sách kết hợp</button>\r\n");
      out.write("                    <button class=\"btn\" style=\"font-size: 14px\">Trực tiếp</button>\r\n");
      out.write("                    <button class=\"btn\" style=\"font-size: 14px\">Đề xuất mới</button>\r\n");
      out.write("                    <button class=\"btn\" style=\"font-size: 14px\">Thịnh hành</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <button class=\"carousel-control-prev d-none d-lg-block\" type=\"button\" data-bs-target=\"#carouselExample\" data-bs-slide=\"prev\" style=\"width: 33px;height=33px;\">\r\n");
      out.write("            <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\" style=\"width: 1rem; height: 1rem;\"></span> \r\n");
      out.write("            <span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <button class=\"carousel-control-next d-none d-lg-block\" type=\"button\" data-bs-target=\"#carouselExample\" data-bs-slide=\"next\" style=\"width: 33px;height=33px;\">\r\n");
      out.write("            <span class=\"carousel-control-next-icon text-white\" style=\"color: white !important; width: 1rem; height: 1rem;\" aria-hidden=\"true\"></span> \r\n");
      out.write("            <span class=\"visually-hidden\">Next</span>\r\n");
      out.write("        </button>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"row my-4\">\r\n");
      out.write("        ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("document.querySelectorAll('.video-container img').forEach(img => {\r\n");
      out.write("    img.addEventListener('mouseenter', function() {\r\n");
      out.write("        const videoLink = this.dataset.videoLink + \"?autoplay=1&mute=1&controls=0&modestbranding=1&fs=1&iv_load_policy=3&rel=0\";\r\n");
      out.write("        const iframe = document.createElement('iframe');\r\n");
      out.write("        iframe.src = videoLink;\r\n");
      out.write("        iframe.title = \"YouTube video\";\r\n");
      out.write("        iframe.allowFullscreen = true;\r\n");
      out.write("        iframe.style.width = '100%';\r\n");
      out.write("        iframe.style.height = '200px';\r\n");
      out.write("        this.replaceWith(iframe);\r\n");
      out.write("\r\n");
      out.write("        iframe.addEventListener('mouseleave', function() {\r\n");
      out.write("            iframe.replaceWith(img);\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /views/TrangChu.jsp(47,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("item");
      // /views/TrangChu.jsp(47,8) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/views/TrangChu.jsp(47,8) '${listViDeo}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${listViDeo}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("            <div class=\"col-lg-4 col-sm-6 col-12 mb-2\">\r\n");
            out.write("                <a href=\"details/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"text-decoration-none\">\r\n");
            out.write("                    <div style=\"border: 0 !important; background-color: transparent !important; color: #fff;\" class=\"card p-0\">\r\n");
            out.write("                        <div class=\"video-container w-100\" style=\"border-radius: 4px; overflow: hidden !important; height: 200px !important\">\r\n");
            out.write("                            <img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.poster}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" data-video-link=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.link}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"rounded w-100 object-fit-cover\" title=\"YouTube video\" style=\"height: 200px\" allowfullscreen>\r\n");
            out.write("                        </div>\r\n");
            out.write("                        <div class=\"row\">\r\n");
            out.write("                            <div class=\"col-lg-2\" style=\"padding-top:15px\">\r\n");
            out.write("                                <img alt=\"\" src=\"../img/tung.jpg\" style=\"width: 36px; height: 36px; border-radius: 50%\">\r\n");
            out.write("                            </div>\r\n");
            out.write("                            <div class=\"col-lg-10\" style=\"padding-left:0\">\r\n");
            out.write("                                <div class=\"card-body p-0\" style=\"background: transparent !important\">\r\n");
            out.write("                                    <div class=\"text-truncate fw-semibold my-2\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("                                    <h5 class=\"text-truncate text-secondary mb-1\" style=\"font-size: 14px\">Nguyễn Thanh Tùng</h5>\r\n");
            out.write("                                    <h5 class=\"text-truncate text-secondary mb-1\" style=\"font-size: 14px\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.formattedViews}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" lượt xem</h5>\r\n");
            out.write("                                </div>\r\n");
            out.write("                            </div>\r\n");
            out.write("                        </div>\r\n");
            out.write("                    </div>\r\n");
            out.write("                </a>\r\n");
            out.write("            </div>\r\n");
            out.write("        ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
